# Generated by Django 5.0.3 on 2024-11-17 21:47

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_account_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=account.models.user_avatar_upload_to
            ),
        ),
    ]
