version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: ./communicator/Dockerfile
    container_name: django-backend
    ports:
      - "8000:8000"
    volumes:
      - ./communicator:/app
    env_file:
      - .env
    depends_on:
      - mysql

  frontend:
    build:
      context: .
      dockerfile: ./frontendCommunicator/Dockerfile
    container_name: react-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app

  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: communicator_db
      MYSQL_PASSWORD: adminpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
