# Generated by Django 5.0.3 on 2024-11-18 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_rename_sender_id_message_sender_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="sender",
            new_name="sender_id",
        ),
        migrations.AlterField(
            model_name="message",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message",
                to="chat.conversation",
            ),
        ),
    ]
